[package]
name = "pixels"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
name = "pixels"
path = "lib.rs"

[dependencies]
base = { workspace = true }
euclid = { workspace = true }
image = { workspace = true }
log = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
makepad_media = { package = "makepad-media", path = "../../../havi-makepad/media", features = ["avif"] }
serde = { workspace = true }
webrender_api = { workspace = true }

[dev-dependencies]
criterion = "0.5"
