[package]
name = "servo_url"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
name = "servo_url"
path = "lib.rs"
doctest = false

[dev-dependencies]
serde_json = { workspace = true }

[dependencies]
encoding_rs = { workspace = true }
hppr-packet = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
servo_arc = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
