[package]
name = "fonts"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
name = "fonts"
path = "lib.rs"

[features]
default = []
tracing = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(ohos_mock)'] }

[dependencies]
app_units = { workspace = true }
base = { workspace = true }
bitflags = { workspace = true }
byteorder = { workspace = true }
content-security-policy = { workspace = true }
euclid = { workspace = true }
fonts_traits = { workspace = true }
freetype-sys = { workspace = true }
harfbuzz-sys = { workspace = true }
itertools = { workspace = true }
icu_properties = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
memmap2 = { workspace = true }
net_traits = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
profile_traits = { workspace = true }
read-fonts = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
servo-tracing = { workspace = true }
servo_allocator = { path = "../allocator" }
servo_arc = { workspace = true }
servo_config = { path = "../config" }
servo_url = { path = "../url" }
skrifa = { workspace = true }
smallvec = { workspace = true }
style = { package = "stylo", git = "https://github.com/servo/stylo", rev = "2f131eb1909c6193a7cfae22e49f288fe9df4fbb" }
unicode-properties = { workspace = true }
unicode-script = { workspace = true }
url = { workspace = true }
webrender_api = { workspace = true }
xml-rs = "0.8"
fontsan = "0.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = { workspace = true }
winapi = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc2-core-foundation = { workspace = true }
objc2-core-graphics = { workspace = true }
objc2-core-text = { workspace = true }

[target.'cfg(any(target_os = "android", target_env = "ohos", all(unix, not(any(target_os = "macos", target_os = "ios")))))'.dependencies]
fontconfig_sys = { package = "yeslogic-fontconfig-sys", version = "6" }
