#!/usr/bin/env bash
# hppr-setup-test.sh - Test hppr-setup:// trust setup page
#
# The hppr-setup page is generated by the protocol handler, so we inject
# the test suite after the page's init() completes.
#
# shellcheck disable=SC1091,SC2034

source "$(dirname "${BASH_SOURCE[0]}")/test-prelude.bash"

TEST_NAME="hppr-setup"
TEST_GROUP="trusttest"
TEST_APP="testapp"

# Local server (browser storage)
start_server
setup_acl "$TEST_GROUP" "$TEST_APP"
create_key

# Remote server (serves content)
start_remote_server
setup_remote_acl "$TEST_GROUP" "$TEST_APP"
create_remote_key
import_remote_content "$SCRIPT_DIR/content" "$TEST_GROUP" "$TEST_APP"
setup_remote_trust "$TEST_GROUP" "$TEST_APP"

log "Remote server at 127.0.0.1:$REMOTE_PORT"

# Navigate to hppr-setup: setup page
start_servo "hppr-setup://$TEST_GROUP/$TEST_APP/{via:127.0.0.1:$REMOTE_PORT}"

# Inject test suite after page init completes
inject_hppr_setup_tests

run_js_tests 30
